(define tol 0.0001)
(define (findx f index)
    (define (enough v1 v2)
        (< (abs (- v1 v2)) tol))
    (define (try guess)
        (let ((next (f guess)))
        (if (enough next guess) next (try next)))
    )
    (try index)
)
(define (avgdamp f )(lambda (x) (/ 2 (+ x (f x)))))
(define (square n) (* n n))
(define (cuberoot n) (findx (avgdamp (lambda (y) (/ n (square y))) ) 1.0))