; (define (sum term a next b)
; (if (> a b) 0 (+ (term a) (sum term (next a) next b))))
(define (inc n) (+ n 1))
(define (cube n) (* n n n))
(define (sum term a next b)
    (define (sumiter a result)
    (if (= a b) result (sumiter (next a) (+ result (term a)))))
    (sumiter a 0))