(define tol 0.0001)
(define (findx f index)
    (define (enough v1 v2)
        (< (abs (- v1 v2)) tol))
    (define (try guess)
        (let ((next (f guess)))
        (if (enough next guess) next (try next)))
    )
    (try index)
)
(define (fin x) (+ 1 (/ 1.0 x)))