(define (iterative-improve enough improve) 
 (lambda (firstguess) 
    (define (try guess)
        (define next (improve guess))
        (if (enough next guess) next (try next))
    )
 (try firstguess)
 )
 )
 (define (enough a b)(< (abs (- a b))0.0001))
(define (sqrt x)
    (define dx 0.00001)
    (define (close-enough? v1 v2)
        (< (abs (- v1 v2)) dx))
    (define (improve guess)
        (average guess (/ x guess))
    (define (average x y)
        (/ (+ x y) 2))
    ((iterative-improve close-enough? improve) 1.0))