(define (runtime) (current-milliseconds))
(define (timePrimeTest n) 
    (newline)
    (display n)
    (startPrimeTest n (runtime)))
(define (startPrimeTest n startTime)
    (if (prime n) (reportPrime (- (runtime) startTime))))
(define (reportPrime cosntTime)
    (display " *** ")
    (display cosntTime))
(define (smallestDivisor n) (findDivisor n 2))
(define (square n) (* n n))
(define (findDivisor n testDivisor)
    (cond ((> (square testDivisor) n) n)
        ((divisor testDivisor n) testDivisor)
        (else (findDivisor n (+ testDivisor 1)))
        ) )
(define (divisor a b) ( = (remainder b a) 0))
(define (prime n ) (= n (smallestDivisor n)))
 (timePrimeTest 1000)