(defun smaller (x y) 
    (if (> x y) y x)
)
(defun bigger (x y)
    (if (> x y) x y)
)
(defun square (x) (* x x))
(defun sum-of-squares (x y) 
    (+ (square x) (square y)))
(defun bigger-sum-of-squares (x y z)
    (sum-of-squares (bigger x y) (bigger (smaller x y) z))
)

(print (bigger-sum-of-squares 1 2 3 ))