(defun make-leaf (symbol weight)
    (list 'leaf symbol weight))
(defun leaf? (object)
    (eq? (car object) 'leaf))
(defun symbol-leaf (x) 
    (cadr x))
(defun weight-leaf (x) 
    (caddr x))
(defun make-code-tree (left right)
    (list left right (append (symbols left) (symbols right)))
    (+ (weight left) (weight rigth)))
(defun left-branch (tree) (car tree))
(defun right-branch (tree) (cadr tree))
(defun symbols (tree) 
    (if (leaf? tree) (list (symbol-leaf tree)) (caddr tree)))
(defun weight (tree) 
    (if (leaf? tree)
        (weight-leaf tree)
        (caddrr tree))) 