
(define (upper-interval x) (car x))
(define (lower-interval x) (cdr x))
(define (make-interval a b )(cons a b))
(define (sub-interval i1 i2)
    (make-interval
        (- (upper-interval i1) (lower-interval i2))
        (- (lower-interval i1) (upper-interval i1))
    )
)
(define (div-interval i1 i2) 
    (if (and (> (upper-interval i2)0)))
)
(define (haszero i) 
(let ((u (upper-interval i))
        (l (lower-interval i)))
(or (and (> u 0) (< l 0)) (= u 0) (= l 0))
)
)