(define (square x) (* x x))
; (define (square-list items) 
;     (if (null? items) () (cons (square (car items)) (cdr items))
; )
; )
; (define list1 (list 1 2 3 4()))
; (define (square-list items)
;     (map square items)
; )
(define (square-list items)
    (map square items)
)