(define (makeSegment x y)
    (cons x y)
)
(define (starSegment s) (car s) )
(define (endSegment s) (cdr s))
(define (makePoint x y) (cons x y ))
(define (x-point point) (car point))
(define (y-point point) (cdr point))
(define (midPoint s )
    (define start (starSegment s))
    (define end (endSegment s))
(makePoint 
    (/ ( + (x-point start) (x-point end)) 2)
    (/ (+ (y-point start) (y-point end))2)
)
)
(define (printPoint p) 
    (newline)
    (display "(")
    (display (x-point p))
    (display ",")
    (display (y-point p))
    (display ")"))

(define p1 (makePoint 1 2))
(define p2 (makePoint 2 4))
(define s (makeSegment p1 p2))
(define mid (midPoint s))