; 为每个框架的构造函数提供选择函数
(define (make-frame1 origin edge1 edge2)
    (list origin edge1 edge2)
)
(define (frame1-origin f)
    (car f)
)
(define (frame1-edge1 f)
    (cadr f)
)
(define (frame1-edge2 f)
    (caddr f)
)
(define (make-frame2 origin edge1 edge2)
    (cons origin (cons edge1 edge2))
)

(define (frame2-origin f)
    (car f)
)
(define (frame2-edge1 f)
    (cadr f)
)
(define (frame2-edge2 f)
    (cddr f)
)