(define (make-vect x y )
    (cons x y)
)
(define (x-vect v)
    (car v)
)
(define (y-vect v)
    (cdr v)
)
(define (op-vect op v1 v2)
   (make-vect (op (x-vect v1) (x-vect v2)) (op (y-vect v1)(y-vect v2)))
)
(define (add-vect v1 v2)
    (op-vect + v1 v2)
)
(define (sub-vect v1 v2)
(op-vect - v1 v2)
)
(define (scale-vect s v1)
    (make-vect (* s (x-vect v1)) (* s (y-vect v1)))
)