(define (element-of-set? x set)
    (cond ((null? set) #f)
        ((equal? x (car set)) #t)
        (else (element-of-set? x (cdr set)))
    )
)
(define (adjoin-set x set)
    (if (element-of-set? x set) set (cons x set))
)
(define (interaction-set set1 set2)
    (cond ((or (null? set1) (null? set2)) '())
    (
        (element-of-set? (car set1) set2)
        (cons (car set1) (interaction-set (cdr set1) set2))
    )
    (else (interaction-set (cdr set1) set2))
    )
)
(define (union-set set1 set2)
    (cond ((and (null? set1) (null? set2) ) '())
    ((null? set1) set2)
    ((null? set2) set1)
    (else (union-set (cdr set1) (adjoin (car set1) set2)))
    )
)