(define (unionset set1 set2)
    (let ((a1 (car set1)
        (a2 (car set2))
    ))
    (cond ((eq? a1 a2) (unionset (cdr set1) set2))
    (< a1 a2) (cons a1 (unionset (cdr set1) set2)))
    ((> a1 a2) (cons a2 (unionset set1 (cdr set2))))
    )
)