(define (m b)
    (lambda (a) 
        (if (>= b a) (begin (set! b (- b a)) b) "err")
    )
)

(define a2 (m  100))
(define (make-withdraw balance)
    (lambda (amount) 
        (if (>= balance amount) 
        (begin (set! balance (- balance amount)) balance)
        "error"
        )
    )
)
(define a1 (make-withdraw  100))
(define (make-bank-account balance)
  (lambda (n)
    (set! balance (+ balance n))
    balance))
(define gates-bank-account (make-bank-account 10)) 